# Generated by Django 2.2.4 on 2022-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20220226_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
