# Generated by Django 2.2.4 on 2022-02-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20220226_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='trader',
            name='city',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
