# Generated by Django 2.2.4 on 2022-02-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20220226_1500'),
        ('login_app', '0004_auto_20220226_1940'),
    ]

    operations = [
    ]
