# Generated by Django 2.2.4 on 2022-02-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_merge_20220227_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='farmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='login_app.Farmer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='login_app.Crop'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='login_app.Trader'),
        ),
    ]
