# Generated by Django 2.2.4 on 2022-02-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20220227_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='login_app.Farmer'),
        ),
    ]
